packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@t3-oss/env-nextjs": ^0.13.8
  "@types/pg": ^8.15.5
  "@web-std/file": ^3.0.3
  "@types/node": ^22.18.12
  dotenv-cli: ^10.0.0
  eslint: ^9.38.0
  pg: ^8.16.3
  postcss: ^8.5.6
  react-hook-form: ^7.65.0
  sharp: ^0.34.4
  sonner: ^2.0.7
  superjson: 2.2.2
  uuid: ^13.0.0
  zod: 4.1.12

catalogs:
  better-auth:
    "@better-auth/cli": 1.4.0-beta.9
    "@better-auth/expo": 1.4.0-beta.9
    better-auth: 1.4.0-beta.9
  drizzle:
    drizzle-kit: ^0.31.5
    drizzle-orm: ^0.44.6
    drizzle-zod: ^0.8.3
  eslint:
    "@eslint/compat": ^1.4.1
    "@eslint/js": ^9.38.0
    eslint: ^9.38.0
  icons:
    "@tabler/icons-react": ^3.35.0
    lucide-react: ^0.546.0
  next:
    "@next/eslint-plugin-next": ^16.0.1
    next: ^16.0.1
  prettier:
    "@ianvs/prettier-plugin-sort-imports": ^4.7.0
    prettier: ^3.6.2
    prettier-plugin-tailwindcss: ^0.6.14
  react19:
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2
    react: 19.2.0
    react-dom: 19.2.0
  tailwindcss:
    "@tailwindcss/postcss": ^4.1.14
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.14
  tanstack:
    "@tanstack/react-form": ^1.23.7
    "@tanstack/react-query": ^5.90.2
  tiptap:
    "@tiptap/pm": ^3.9.1
    "@tiptap/react": ^3.9.1
    "@tiptap/starter-kit": ^3.9.1
    "@tiptap/suggestion": ^3.9.1
  trpc:
    "@trpc/client": ^11.6.0
    "@trpc/react-query": ^11.7.1
    "@trpc/server": 11.7.1
  turbo:
    eslint-plugin-turbo: ^2.5.8
    turbo: ^2.5.8
  typescript:
    typescript: ^5.9.3
  uploadthing:
    "@uploadthing/expo": ^7.2.6
    "@uploadthing/react": ^7.3.3
    uploadthing: ^7.7.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild

overrides:
  "@types/minimatch": 5.1.2

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
