packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@jimp/js-jpeg': ^1.6.0
  '@jimp/js-png': ^1.6.0
  '@radix-ui/react-aspect-ratio': ^1.1.8
  '@radix-ui/react-dialog': 1.1.15
  '@squoosh/lib': ^0.5.3
  '@t3-oss/env-nextjs': ^0.13.8
  '@tanstack/react-virtual': ^3.13.12
  '@types/node': ^22.18.12
  '@types/react': ^19.1.17
  '@web-std/file': ^3.0.3
  cmdk: ^1.1.1
  dotenv-cli: ^10.0.0
  drizzle-orm: ^0.44.7
  jimp: ^1.6.0
  nativewind: 5.0.0-preview.2
  next-themes: ^0.4.6
  open-graph-scraper: ^6.10.0
  optional: ^0.1.4
  postcss: ^8.5.6
  react: ^19.1.0
  react-dom: ^19.1.0
  react-dropzone: ^14.3.8
  react-hook-form: ^7.65.0
  react-intersection-observer: ^10.0.0
  react-native-css: 3.0.1
  react-native-reanimated: 4.1.5
  react-native-safe-area-context: 5.6.2
  sonner: ^2.0.7
  superjson: 2.2.2
  use-debounce: ^10.0.6
  uuid: 13.0.0
  zod: 4.1.12

catalogMode: strict

catalogs:
  better-auth:
    '@better-auth/cli': 1.4.0-beta.9
    '@better-auth/expo': 1.4.0-beta.9
    better-auth: 1.4.0-beta.9
  drizzle:
    drizzle-kit: ^0.31.5
    drizzle-orm: ^0.44.6
    drizzle-zod: ^0.8.3
  eslint:
    '@eslint/compat': ^1.4.1
    '@eslint/js': ^9.38.0
    eslint: ^9.38.0
  expo:
    expo: ^54.0.25
    expo-linking: ~8.0.9
    expo-router: ~6.0.14
    expo-splash-screen: ^31.0.11
    react-native: 0.81.5
    react-native-gesture-handler: ~2.28.0
    react-native-reanimated: ~4.1.3
    react-native-safe-area-context: 5.6.2
    react-native-screens: 4.16.0
  icons:
    '@tabler/icons-react': ^3.35.0
    lucide-react: ^0.546.0
  next:
    '@next/eslint-plugin-next': ^16.0.1
    next: ^16.0.1
  prettier:
    '@ianvs/prettier-plugin-sort-imports': ^4.7.0
    prettier: ^3.6.2
    prettier-plugin-tailwindcss: ^0.6.14
  react19:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    react: 19.2.0
    react-dom: 19.2.0
  tailwindcss:
    '@tailwindcss/postcss': ^4.1.14
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.14
  tanstack:
    '@tanstack/react-form': ^1.23.7
    '@tanstack/react-query': ^5.90.2
  tiptap:
    '@tiptap/extension-mention': ^3.9.1
    '@tiptap/pm': ^3.9.1
    '@tiptap/react': ^3.9.1
    '@tiptap/starter-kit': ^3.9.1
    '@tiptap/suggestion': ^3.9.1
  trpc:
    '@trpc/client': ^11.6.0
    '@trpc/react-query': ^11.7.1
    '@trpc/server': 11.7.1
    '@trpc/tanstack-react-query': ^11.7.1
  turbo:
    eslint-plugin-turbo: ^2.5.8
    turbo: ^2.5.8
  typescript:
    typescript: ^5.9.3
  uploadthing:
    '@uploadthing/expo': ^7.2.6
    '@uploadthing/react': ^7.3.3
    uploadthing: 7.7.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss

supportedArchitectures:
  cpu: [x64]
  os: [win32]
